sudo: false

language: php

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.2
  include:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_COVERAGE=true
    - php: 7
    - php: hhvm
    
before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0; fi

script:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then phpunit --coverage-clover clover.xml tests; fi
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpunit tests; fi
  
after_success:
  - if [[ $EXECUTE_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi
  